server:
  port: 80


spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      routes:
        - id: driver_route
          uri: lb://CLOUD-DRIVER-SERVICE
          predicates:
            - Path=/driver/**
        - id: passenger_route
          uri: lb://CLOUD-PASSENGER-SERVICE
          predicates:
            - Path=/passenger/**
        - id: bill_route
          uri: lb://CLOUD-BILL-SERVICE
          predicates:
            - Path=/bill/**



eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9000/eureka
